// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package db

import (
	"context"
)

const countArtifacts = `-- name: CountArtifacts :one
SELECT COUNT(*) FROM artifact
`

func (q *Queries) CountArtifacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifact (job_version_id, name, content_type, storage_backend, storage_path, status)
VALUES ($1, $2, $3, $4, $5, 'PENDING')
RETURNING id, job_version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at
`

type CreateArtifactParams struct {
	JobVersionID   int64   `json:"job_version_id"`
	Name           string  `json:"name"`
	ContentType    *string `json:"content_type"`
	StorageBackend string  `json:"storage_backend"`
	StoragePath    string  `json:"storage_path"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.JobVersionID,
		arg.Name,
		arg.ContentType,
		arg.StorageBackend,
		arg.StoragePath,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.JobVersionID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifact WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArtifact, id)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, job_version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at FROM artifact WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id int64) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.JobVersionID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, job_version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at FROM artifact
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListArtifactsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.JobVersionID,
			&i.Name,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageBackend,
			&i.StoragePath,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByJobVersion = `-- name: ListArtifactsByJobVersion :many
SELECT id, job_version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at FROM artifact
WHERE job_version_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListArtifactsByJobVersion(ctx context.Context, jobVersionID int64) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByJobVersion, jobVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.JobVersionID,
			&i.Name,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageBackend,
			&i.StoragePath,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactStatus = `-- name: UpdateArtifactStatus :one
UPDATE artifact
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, job_version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at
`

type UpdateArtifactStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateArtifactStatus(ctx context.Context, arg UpdateArtifactStatusParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, updateArtifactStatus, arg.ID, arg.Status)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.JobVersionID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArtifactStored = `-- name: UpdateArtifactStored :one
UPDATE artifact
SET storage_path = $2,
    size_bytes   = $3,
    status       = $4,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, job_version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at
`

type UpdateArtifactStoredParams struct {
	ID          int64  `json:"id"`
	StoragePath string `json:"storage_path"`
	SizeBytes   *int64 `json:"size_bytes"`
	Status      string `json:"status"`
}

func (q *Queries) UpdateArtifactStored(ctx context.Context, arg UpdateArtifactStoredParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, updateArtifactStored,
		arg.ID,
		arg.StoragePath,
		arg.SizeBytes,
		arg.Status,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.JobVersionID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
