// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
)

const countArtifactsForJobVersion = `-- name: CountArtifactsForJobVersion :one
SELECT COUNT(*) FROM artifact WHERE job_version_id = $1
`

func (q *Queries) CountArtifactsForJobVersion(ctx context.Context, jobVersionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifactsForJobVersion, jobVersionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM job
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO job (name, description, template_version_id, latest_version_number)
VALUES ($1, $2, $3, 0)
RETURNING id, name, description, template_version_id, latest_version_number, created_at, updated_at
`

type CreateJobParams struct {
	Name              string  `json:"name"`
	Description       *string `json:"description"`
	TemplateVersionID int64   `json:"template_version_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.Name, arg.Description, arg.TemplateVersionID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TemplateVersionID,
		&i.LatestVersionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJobVersion = `-- name: CreateJobVersion :one
INSERT INTO job_version (job_id, version_number, docker_image, git_url, git_ref, git_subpath, run_config, template_version_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, job_id, version_number, docker_image, git_url, git_ref, git_subpath, run_config, template_version_id, created_at
`

type CreateJobVersionParams struct {
	JobID             int64   `json:"job_id"`
	VersionNumber     int32   `json:"version_number"`
	DockerImage       string  `json:"docker_image"`
	GitUrl            string  `json:"git_url"`
	GitRef            string  `json:"git_ref"`
	GitSubpath        *string `json:"git_subpath"`
	RunConfig         *string `json:"run_config"`
	TemplateVersionID int64   `json:"template_version_id"`
}

func (q *Queries) CreateJobVersion(ctx context.Context, arg CreateJobVersionParams) (JobVersion, error) {
	row := q.db.QueryRow(ctx, createJobVersion,
		arg.JobID,
		arg.VersionNumber,
		arg.DockerImage,
		arg.GitUrl,
		arg.GitRef,
		arg.GitSubpath,
		arg.RunConfig,
		arg.TemplateVersionID,
	)
	var i JobVersion
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VersionNumber,
		&i.DockerImage,
		&i.GitUrl,
		&i.GitRef,
		&i.GitSubpath,
		&i.RunConfig,
		&i.TemplateVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM job WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, name, description, template_version_id, latest_version_number, created_at, updated_at FROM job WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TemplateVersionID,
		&i.LatestVersionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByName = `-- name: GetJobByName :one
SELECT id, name, description, template_version_id, latest_version_number, created_at, updated_at FROM job WHERE name = $1
`

func (q *Queries) GetJobByName(ctx context.Context, name string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByName, name)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TemplateVersionID,
		&i.LatestVersionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobVersionByID = `-- name: GetJobVersionByID :one
SELECT id, job_id, version_number, docker_image, git_url, git_ref, git_subpath, run_config, template_version_id, created_at FROM job_version WHERE id = $1
`

func (q *Queries) GetJobVersionByID(ctx context.Context, id int64) (JobVersion, error) {
	row := q.db.QueryRow(ctx, getJobVersionByID, id)
	var i JobVersion
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VersionNumber,
		&i.DockerImage,
		&i.GitUrl,
		&i.GitRef,
		&i.GitSubpath,
		&i.RunConfig,
		&i.TemplateVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getJobVersionByJobAndNumber = `-- name: GetJobVersionByJobAndNumber :one
SELECT id, job_id, version_number, docker_image, git_url, git_ref, git_subpath, run_config, template_version_id, created_at FROM job_version
WHERE job_id = $1 AND version_number = $2
`

type GetJobVersionByJobAndNumberParams struct {
	JobID         int64 `json:"job_id"`
	VersionNumber int32 `json:"version_number"`
}

func (q *Queries) GetJobVersionByJobAndNumber(ctx context.Context, arg GetJobVersionByJobAndNumberParams) (JobVersion, error) {
	row := q.db.QueryRow(ctx, getJobVersionByJobAndNumber, arg.JobID, arg.VersionNumber)
	var i JobVersion
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.VersionNumber,
		&i.DockerImage,
		&i.GitUrl,
		&i.GitRef,
		&i.GitSubpath,
		&i.RunConfig,
		&i.TemplateVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const incrementJobVersion = `-- name: IncrementJobVersion :one
UPDATE job
SET latest_version_number = latest_version_number + 1,
    updated_at             = NOW()
WHERE id = $1
RETURNING latest_version_number
`

func (q *Queries) IncrementJobVersion(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementJobVersion, id)
	var latest_version_number int32
	err := row.Scan(&latest_version_number)
	return latest_version_number, err
}

const listJobVersions = `-- name: ListJobVersions :many
SELECT id, job_id, version_number, docker_image, git_url, git_ref, git_subpath, run_config, template_version_id, created_at FROM job_version
WHERE job_id = $1
ORDER BY version_number ASC
`

func (q *Queries) ListJobVersions(ctx context.Context, jobID int64) ([]JobVersion, error) {
	rows, err := q.db.Query(ctx, listJobVersions, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobVersion
	for rows.Next() {
		var i JobVersion
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.VersionNumber,
			&i.DockerImage,
			&i.GitUrl,
			&i.GitRef,
			&i.GitSubpath,
			&i.RunConfig,
			&i.TemplateVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, name, description, template_version_id, latest_version_number, created_at, updated_at FROM job
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TemplateVersionID,
			&i.LatestVersionNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE job
SET description = $2,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, description, template_version_id, latest_version_number, created_at, updated_at
`

type UpdateJobParams struct {
	ID          int64   `json:"id"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob, arg.ID, arg.Description)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TemplateVersionID,
		&i.LatestVersionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
