// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RegistryArtifact struct {
	ID          int64              `json:"id"`
	FullName    string             `json:"full_name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RegistryArtifactFile struct {
	ID             int64              `json:"id"`
	VersionID      int64              `json:"version_id"`
	Name           string             `json:"name"`
	ContentType    *string            `json:"content_type"`
	SizeBytes      *int64             `json:"size_bytes"`
	StorageBackend string             `json:"storage_backend"`
	StoragePath    string             `json:"storage_path"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RegistryArtifactTag struct {
	ID         int64              `json:"id"`
	ArtifactID int64              `json:"artifact_id"`
	Tag        string             `json:"tag"`
	VersionID  int64              `json:"version_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RegistryArtifactType struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RegistryArtifactTypeMap struct {
	ID         int64              `json:"id"`
	ArtifactID int64              `json:"artifact_id"`
	TypeID     int64              `json:"type_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RegistryArtifactVersion struct {
	ID         int64              `json:"id"`
	ArtifactID int64              `json:"artifact_id"`
	Major      int32              `json:"major"`
	Minor      int32              `json:"minor"`
	Patch      int32              `json:"patch"`
	Config     *string            `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
