// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_tags.sql

package db

import (
	"context"
)

const deleteArtifactTag = `-- name: DeleteArtifactTag :exec
DELETE FROM registry_artifact_tag
WHERE artifact_id = $1 AND tag = $2
`

type DeleteArtifactTagParams struct {
	ArtifactID int64  `json:"artifact_id"`
	Tag        string `json:"tag"`
}

func (q *Queries) DeleteArtifactTag(ctx context.Context, arg DeleteArtifactTagParams) error {
	_, err := q.db.Exec(ctx, deleteArtifactTag, arg.ArtifactID, arg.Tag)
	return err
}

const getArtifactTag = `-- name: GetArtifactTag :one
SELECT id, artifact_id, tag, version_id, created_at, updated_at FROM registry_artifact_tag
WHERE artifact_id = $1 AND tag = $2
`

type GetArtifactTagParams struct {
	ArtifactID int64  `json:"artifact_id"`
	Tag        string `json:"tag"`
}

func (q *Queries) GetArtifactTag(ctx context.Context, arg GetArtifactTagParams) (RegistryArtifactTag, error) {
	row := q.db.QueryRow(ctx, getArtifactTag, arg.ArtifactID, arg.Tag)
	var i RegistryArtifactTag
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Tag,
		&i.VersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactTags = `-- name: ListArtifactTags :many
SELECT id, artifact_id, tag, version_id, created_at, updated_at FROM registry_artifact_tag
WHERE artifact_id = $1
ORDER BY tag ASC
`

func (q *Queries) ListArtifactTags(ctx context.Context, artifactID int64) ([]RegistryArtifactTag, error) {
	rows, err := q.db.Query(ctx, listArtifactTags, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifactTag
	for rows.Next() {
		var i RegistryArtifactTag
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Tag,
			&i.VersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactTagsByVersionID = `-- name: ListArtifactTagsByVersionID :many
SELECT id, artifact_id, tag, version_id, created_at, updated_at FROM registry_artifact_tag
WHERE version_id = $1
ORDER BY tag ASC
`

func (q *Queries) ListArtifactTagsByVersionID(ctx context.Context, versionID int64) ([]RegistryArtifactTag, error) {
	rows, err := q.db.Query(ctx, listArtifactTagsByVersionID, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifactTag
	for rows.Next() {
		var i RegistryArtifactTag
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Tag,
			&i.VersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByVersionIDs = `-- name: ListTagsByVersionIDs :many
SELECT id, artifact_id, tag, version_id, created_at, updated_at FROM registry_artifact_tag
WHERE version_id = ANY($1::bigint[])
ORDER BY version_id ASC, tag ASC
`

func (q *Queries) ListTagsByVersionIDs(ctx context.Context, dollar_1 []int64) ([]RegistryArtifactTag, error) {
	rows, err := q.db.Query(ctx, listTagsByVersionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifactTag
	for rows.Next() {
		var i RegistryArtifactTag
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Tag,
			&i.VersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtifactTag = `-- name: UpsertArtifactTag :one
INSERT INTO registry_artifact_tag (artifact_id, tag, version_id)
VALUES ($1, $2, $3)
ON CONFLICT (artifact_id, tag) DO UPDATE
    SET version_id = EXCLUDED.version_id,
        updated_at = NOW()
RETURNING id, artifact_id, tag, version_id, created_at, updated_at
`

type UpsertArtifactTagParams struct {
	ArtifactID int64  `json:"artifact_id"`
	Tag        string `json:"tag"`
	VersionID  int64  `json:"version_id"`
}

func (q *Queries) UpsertArtifactTag(ctx context.Context, arg UpsertArtifactTagParams) (RegistryArtifactTag, error) {
	row := q.db.QueryRow(ctx, upsertArtifactTag, arg.ArtifactID, arg.Tag, arg.VersionID)
	var i RegistryArtifactTag
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Tag,
		&i.VersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
