// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_versions.sql

package db

import (
	"context"
)

const createArtifactVersion = `-- name: CreateArtifactVersion :one
INSERT INTO registry_artifact_version (artifact_id, major, minor, patch, config)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, artifact_id, major, minor, patch, config, created_at
`

type CreateArtifactVersionParams struct {
	ArtifactID int64   `json:"artifact_id"`
	Major      int32   `json:"major"`
	Minor      int32   `json:"minor"`
	Patch      int32   `json:"patch"`
	Config     *string `json:"config"`
}

func (q *Queries) CreateArtifactVersion(ctx context.Context, arg CreateArtifactVersionParams) (RegistryArtifactVersion, error) {
	row := q.db.QueryRow(ctx, createArtifactVersion,
		arg.ArtifactID,
		arg.Major,
		arg.Minor,
		arg.Patch,
		arg.Config,
	)
	var i RegistryArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Major,
		&i.Minor,
		&i.Patch,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifactVersion = `-- name: DeleteArtifactVersion :exec
DELETE FROM registry_artifact_version WHERE id = $1
`

func (q *Queries) DeleteArtifactVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArtifactVersion, id)
	return err
}

const getArtifactVersion = `-- name: GetArtifactVersion :one
SELECT id, artifact_id, major, minor, patch, config, created_at FROM registry_artifact_version
WHERE artifact_id = $1
  AND major = $2
  AND minor = $3
  AND patch = $4
`

type GetArtifactVersionParams struct {
	ArtifactID int64 `json:"artifact_id"`
	Major      int32 `json:"major"`
	Minor      int32 `json:"minor"`
	Patch      int32 `json:"patch"`
}

func (q *Queries) GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (RegistryArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getArtifactVersion,
		arg.ArtifactID,
		arg.Major,
		arg.Minor,
		arg.Patch,
	)
	var i RegistryArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Major,
		&i.Minor,
		&i.Patch,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactVersionByID = `-- name: GetArtifactVersionByID :one
SELECT id, artifact_id, major, minor, patch, config, created_at FROM registry_artifact_version WHERE id = $1
`

func (q *Queries) GetArtifactVersionByID(ctx context.Context, id int64) (RegistryArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getArtifactVersionByID, id)
	var i RegistryArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Major,
		&i.Minor,
		&i.Patch,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
SELECT id, artifact_id, major, minor, patch, config, created_at FROM registry_artifact_version
WHERE artifact_id = $1
ORDER BY major DESC, minor DESC, patch DESC
`

func (q *Queries) ListArtifactVersions(ctx context.Context, artifactID int64) ([]RegistryArtifactVersion, error) {
	rows, err := q.db.Query(ctx, listArtifactVersions, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifactVersion
	for rows.Next() {
		var i RegistryArtifactVersion
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Major,
			&i.Minor,
			&i.Patch,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
