// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArtifactsWithoutFiles = `-- name: CountArtifactsWithoutFiles :one
SELECT COUNT(*) FROM registry_artifact ra
WHERE ra.created_at < $1
  AND EXISTS (SELECT 1 FROM registry_artifact_version rav WHERE rav.artifact_id = ra.id)
  AND NOT EXISTS (
    SELECT 1 FROM registry_artifact_version rav2
    JOIN registry_artifact_file raf ON raf.version_id = rav2.id
    WHERE rav2.artifact_id = ra.id
  )
`

func (q *Queries) CountArtifactsWithoutFiles(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifactsWithoutFiles, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmptyArtifacts = `-- name: CountEmptyArtifacts :one
SELECT COUNT(*) FROM registry_artifact ra
WHERE ra.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM registry_artifact_version rav WHERE rav.artifact_id = ra.id)
`

func (q *Queries) CountEmptyArtifacts(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countEmptyArtifacts, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistryArtifacts = `-- name: CountRegistryArtifacts :one
SELECT COUNT(*) FROM registry_artifact
`

func (q *Queries) CountRegistryArtifacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistryArtifacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistryArtifactsByName = `-- name: CountRegistryArtifactsByName :one
SELECT COUNT(*) FROM registry_artifact
WHERE full_name ILIKE $1
`

func (q *Queries) CountRegistryArtifactsByName(ctx context.Context, fullName string) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistryArtifactsByName, fullName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistryArtifactsByTag = `-- name: CountRegistryArtifactsByTag :one
SELECT COUNT(*) FROM registry_artifact ra
JOIN registry_artifact_tag rat ON rat.artifact_id = ra.id
WHERE rat.tag = $1
`

func (q *Queries) CountRegistryArtifactsByTag(ctx context.Context, tag string) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistryArtifactsByTag, tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistryArtifactsByTypes = `-- name: CountRegistryArtifactsByTypes :one
SELECT COUNT(DISTINCT ra.id) FROM registry_artifact ra
JOIN registry_artifact_type_map ratm ON ratm.artifact_id = ra.id
JOIN registry_artifact_type rat ON rat.id = ratm.type_id
WHERE rat.name = ANY($1::text[])
`

func (q *Queries) CountRegistryArtifactsByTypes(ctx context.Context, dollar_1 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistryArtifactsByTypes, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegistryArtifact = `-- name: CreateRegistryArtifact :one
INSERT INTO registry_artifact (full_name, description)
VALUES ($1, $2)
RETURNING id, full_name, description, created_at, updated_at
`

type CreateRegistryArtifactParams struct {
	FullName    string  `json:"full_name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateRegistryArtifact(ctx context.Context, arg CreateRegistryArtifactParams) (RegistryArtifact, error) {
	row := q.db.QueryRow(ctx, createRegistryArtifact, arg.FullName, arg.Description)
	var i RegistryArtifact
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtifactsWithoutFiles = `-- name: DeleteArtifactsWithoutFiles :execrows
DELETE FROM registry_artifact
WHERE registry_artifact.created_at < $1
  AND EXISTS (SELECT 1 FROM registry_artifact_version rav WHERE rav.artifact_id = registry_artifact.id)
  AND NOT EXISTS (
    SELECT 1 FROM registry_artifact_version rav2
    JOIN registry_artifact_file raf ON raf.version_id = rav2.id
    WHERE rav2.artifact_id = registry_artifact.id
  )
  AND NOT EXISTS (SELECT 1 FROM registry_artifact_tag rat WHERE rat.artifact_id = registry_artifact.id AND rat.tag = $2)
`

type DeleteArtifactsWithoutFilesParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Tag       string             `json:"tag"`
}

func (q *Queries) DeleteArtifactsWithoutFiles(ctx context.Context, arg DeleteArtifactsWithoutFilesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifactsWithoutFiles, arg.CreatedAt, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmptyArtifacts = `-- name: DeleteEmptyArtifacts :execrows
DELETE FROM registry_artifact
WHERE registry_artifact.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM registry_artifact_version rav WHERE rav.artifact_id = registry_artifact.id)
  AND NOT EXISTS (SELECT 1 FROM registry_artifact_tag rat WHERE rat.artifact_id = registry_artifact.id AND rat.tag = $2)
`

type DeleteEmptyArtifactsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Tag       string             `json:"tag"`
}

func (q *Queries) DeleteEmptyArtifacts(ctx context.Context, arg DeleteEmptyArtifactsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmptyArtifacts, arg.CreatedAt, arg.Tag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRegistryArtifact = `-- name: DeleteRegistryArtifact :exec
DELETE FROM registry_artifact WHERE id = $1
`

func (q *Queries) DeleteRegistryArtifact(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRegistryArtifact, id)
	return err
}

const getRegistryArtifact = `-- name: GetRegistryArtifact :one
SELECT id, full_name, description, created_at, updated_at FROM registry_artifact WHERE id = $1
`

func (q *Queries) GetRegistryArtifact(ctx context.Context, id int64) (RegistryArtifact, error) {
	row := q.db.QueryRow(ctx, getRegistryArtifact, id)
	var i RegistryArtifact
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistryArtifactByName = `-- name: GetRegistryArtifactByName :one
SELECT id, full_name, description, created_at, updated_at FROM registry_artifact WHERE full_name = $1
`

func (q *Queries) GetRegistryArtifactByName(ctx context.Context, fullName string) (RegistryArtifact, error) {
	row := q.db.QueryRow(ctx, getRegistryArtifactByName, fullName)
	var i RegistryArtifact
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactsWithoutFiles = `-- name: ListArtifactsWithoutFiles :many
SELECT ra.id, ra.full_name, ra.description, ra.created_at, ra.updated_at FROM registry_artifact ra
WHERE ra.created_at < $1
  AND EXISTS (SELECT 1 FROM registry_artifact_version rav WHERE rav.artifact_id = ra.id)
  AND NOT EXISTS (
    SELECT 1 FROM registry_artifact_version rav2
    JOIN registry_artifact_file raf ON raf.version_id = rav2.id
    WHERE rav2.artifact_id = ra.id
  )
ORDER BY ra.created_at DESC
LIMIT $2 OFFSET $3
`

type ListArtifactsWithoutFilesParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
}

func (q *Queries) ListArtifactsWithoutFiles(ctx context.Context, arg ListArtifactsWithoutFilesParams) ([]RegistryArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsWithoutFiles, arg.CreatedAt, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifact
	for rows.Next() {
		var i RegistryArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmptyArtifacts = `-- name: ListEmptyArtifacts :many
SELECT ra.id, ra.full_name, ra.description, ra.created_at, ra.updated_at FROM registry_artifact ra
WHERE ra.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM registry_artifact_version rav WHERE rav.artifact_id = ra.id)
ORDER BY ra.created_at DESC
LIMIT $2 OFFSET $3
`

type ListEmptyArtifactsParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
}

func (q *Queries) ListEmptyArtifacts(ctx context.Context, arg ListEmptyArtifactsParams) ([]RegistryArtifact, error) {
	rows, err := q.db.Query(ctx, listEmptyArtifacts, arg.CreatedAt, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifact
	for rows.Next() {
		var i RegistryArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistryArtifacts = `-- name: ListRegistryArtifacts :many
SELECT id, full_name, description, created_at, updated_at FROM registry_artifact
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRegistryArtifactsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRegistryArtifacts(ctx context.Context, arg ListRegistryArtifactsParams) ([]RegistryArtifact, error) {
	rows, err := q.db.Query(ctx, listRegistryArtifacts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifact
	for rows.Next() {
		var i RegistryArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistryArtifactsByName = `-- name: ListRegistryArtifactsByName :many
SELECT id, full_name, description, created_at, updated_at FROM registry_artifact
WHERE full_name ILIKE $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRegistryArtifactsByNameParams struct {
	FullName string `json:"full_name"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListRegistryArtifactsByName(ctx context.Context, arg ListRegistryArtifactsByNameParams) ([]RegistryArtifact, error) {
	rows, err := q.db.Query(ctx, listRegistryArtifactsByName, arg.FullName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifact
	for rows.Next() {
		var i RegistryArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistryArtifactsByTag = `-- name: ListRegistryArtifactsByTag :many
SELECT ra.id, ra.full_name, ra.description, ra.created_at, ra.updated_at FROM registry_artifact ra
JOIN registry_artifact_tag rat ON rat.artifact_id = ra.id
WHERE rat.tag = $1
ORDER BY ra.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRegistryArtifactsByTagParams struct {
	Tag    string `json:"tag"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListRegistryArtifactsByTag(ctx context.Context, arg ListRegistryArtifactsByTagParams) ([]RegistryArtifact, error) {
	rows, err := q.db.Query(ctx, listRegistryArtifactsByTag, arg.Tag, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifact
	for rows.Next() {
		var i RegistryArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistryArtifactsByTypes = `-- name: ListRegistryArtifactsByTypes :many
SELECT DISTINCT ra.id, ra.full_name, ra.description, ra.created_at, ra.updated_at FROM registry_artifact ra
JOIN registry_artifact_type_map ratm ON ratm.artifact_id = ra.id
JOIN registry_artifact_type rat ON rat.id = ratm.type_id
WHERE rat.name = ANY($1::text[])
ORDER BY ra.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRegistryArtifactsByTypesParams struct {
	Column1 []string `json:"column_1"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

func (q *Queries) ListRegistryArtifactsByTypes(ctx context.Context, arg ListRegistryArtifactsByTypesParams) ([]RegistryArtifact, error) {
	rows, err := q.db.Query(ctx, listRegistryArtifactsByTypes, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifact
	for rows.Next() {
		var i RegistryArtifact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRegistryArtifact = `-- name: UpdateRegistryArtifact :one
UPDATE registry_artifact
SET description = $2,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, full_name, description, created_at, updated_at
`

type UpdateRegistryArtifactParams struct {
	ID          int64   `json:"id"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateRegistryArtifact(ctx context.Context, arg UpdateRegistryArtifactParams) (RegistryArtifact, error) {
	row := q.db.QueryRow(ctx, updateRegistryArtifact, arg.ID, arg.Description)
	var i RegistryArtifact
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
