// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_metrics.sql

package db

import (
	"context"
)

const countArtifactsByType = `-- name: CountArtifactsByType :many
SELECT rat.name AS type_name, COUNT(ratm.artifact_id) AS artifact_count
FROM registry_artifact_type rat
LEFT JOIN registry_artifact_type_map ratm ON ratm.type_id = rat.id
GROUP BY rat.name
ORDER BY rat.name
`

type CountArtifactsByTypeRow struct {
	TypeName      string `json:"type_name"`
	ArtifactCount int64  `json:"artifact_count"`
}

func (q *Queries) CountArtifactsByType(ctx context.Context) ([]CountArtifactsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countArtifactsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountArtifactsByTypeRow
	for rows.Next() {
		var i CountArtifactsByTypeRow
		if err := rows.Scan(&i.TypeName, &i.ArtifactCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countArtifactsWithoutTags = `-- name: CountArtifactsWithoutTags :one
SELECT COUNT(*) FROM registry_artifact ra
WHERE NOT EXISTS (
    SELECT 1 FROM registry_artifact_tag rat WHERE rat.artifact_id = ra.id
)
`

func (q *Queries) CountArtifactsWithoutTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifactsWithoutTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArtifactsWithoutVersions = `-- name: CountArtifactsWithoutVersions :one
SELECT COUNT(*) FROM registry_artifact ra
WHERE NOT EXISTS (
    SELECT 1 FROM registry_artifact_version rav WHERE rav.artifact_id = ra.id
)
`

func (q *Queries) CountArtifactsWithoutVersions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifactsWithoutVersions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistryFilesByStatus = `-- name: CountRegistryFilesByStatus :many
SELECT status, COUNT(*) AS count
FROM registry_artifact_file
GROUP BY status
`

type CountRegistryFilesByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountRegistryFilesByStatus(ctx context.Context) ([]CountRegistryFilesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countRegistryFilesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRegistryFilesByStatusRow
	for rows.Next() {
		var i CountRegistryFilesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRegistryTags = `-- name: CountRegistryTags :one
SELECT COUNT(*) FROM registry_artifact_tag
`

func (q *Queries) CountRegistryTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistryTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistryVersions = `-- name: CountRegistryVersions :one
SELECT COUNT(*) FROM registry_artifact_version
`

func (q *Queries) CountRegistryVersions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistryVersions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumRegistryStorageBytes = `-- name: SumRegistryStorageBytes :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint AS total_storage_bytes
FROM registry_artifact_file
WHERE status = 'AVAILABLE'
`

func (q *Queries) SumRegistryStorageBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumRegistryStorageBytes)
	var total_storage_bytes int64
	err := row.Scan(&total_storage_bytes)
	return total_storage_bytes, err
}
