// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_artifact_type_map.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignArtifactType = `-- name: AssignArtifactType :exec
INSERT INTO registry_artifact_type_map (artifact_id, type_id)
VALUES ($1, $2)
ON CONFLICT (artifact_id, type_id) DO NOTHING
`

type AssignArtifactTypeParams struct {
	ArtifactID int64 `json:"artifact_id"`
	TypeID     int64 `json:"type_id"`
}

func (q *Queries) AssignArtifactType(ctx context.Context, arg AssignArtifactTypeParams) error {
	_, err := q.db.Exec(ctx, assignArtifactType, arg.ArtifactID, arg.TypeID)
	return err
}

const getArtifactTypeAssignment = `-- name: GetArtifactTypeAssignment :one
SELECT id, artifact_id, type_id, created_at FROM registry_artifact_type_map
WHERE artifact_id = $1 AND type_id = $2
`

type GetArtifactTypeAssignmentParams struct {
	ArtifactID int64 `json:"artifact_id"`
	TypeID     int64 `json:"type_id"`
}

func (q *Queries) GetArtifactTypeAssignment(ctx context.Context, arg GetArtifactTypeAssignmentParams) (RegistryArtifactTypeMap, error) {
	row := q.db.QueryRow(ctx, getArtifactTypeAssignment, arg.ArtifactID, arg.TypeID)
	var i RegistryArtifactTypeMap
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.TypeID,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactTypesByArtifactID = `-- name: ListArtifactTypesByArtifactID :many
SELECT rat.id, rat.name, rat.description, rat.created_at, rat.updated_at FROM registry_artifact_type rat
JOIN registry_artifact_type_map ratm ON ratm.type_id = rat.id
WHERE ratm.artifact_id = $1
ORDER BY rat.name ASC
`

func (q *Queries) ListArtifactTypesByArtifactID(ctx context.Context, artifactID int64) ([]RegistryArtifactType, error) {
	rows, err := q.db.Query(ctx, listArtifactTypesByArtifactID, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifactType
	for rows.Next() {
		var i RegistryArtifactType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactTypesByArtifactIDs = `-- name: ListArtifactTypesByArtifactIDs :many
SELECT ratm.artifact_id, rat.id, rat.name, rat.description, rat.created_at, rat.updated_at
FROM registry_artifact_type rat
JOIN registry_artifact_type_map ratm ON ratm.type_id = rat.id
WHERE ratm.artifact_id = ANY($1::bigint[])
ORDER BY ratm.artifact_id, rat.name ASC
`

type ListArtifactTypesByArtifactIDsRow struct {
	ArtifactID  int64              `json:"artifact_id"`
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListArtifactTypesByArtifactIDs(ctx context.Context, dollar_1 []int64) ([]ListArtifactTypesByArtifactIDsRow, error) {
	rows, err := q.db.Query(ctx, listArtifactTypesByArtifactIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtifactTypesByArtifactIDsRow
	for rows.Next() {
		var i ListArtifactTypesByArtifactIDsRow
		if err := rows.Scan(
			&i.ArtifactID,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeArtifactType = `-- name: RemoveArtifactType :exec
DELETE FROM registry_artifact_type_map
WHERE artifact_id = $1 AND type_id = $2
`

type RemoveArtifactTypeParams struct {
	ArtifactID int64 `json:"artifact_id"`
	TypeID     int64 `json:"type_id"`
}

func (q *Queries) RemoveArtifactType(ctx context.Context, arg RemoveArtifactTypeParams) error {
	_, err := q.db.Exec(ctx, removeArtifactType, arg.ArtifactID, arg.TypeID)
	return err
}
