// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_types.sql

package db

import (
	"context"
)

const createArtifactType = `-- name: CreateArtifactType :one
INSERT INTO registry_artifact_type (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateArtifactTypeParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateArtifactType(ctx context.Context, arg CreateArtifactTypeParams) (RegistryArtifactType, error) {
	row := q.db.QueryRow(ctx, createArtifactType, arg.Name, arg.Description)
	var i RegistryArtifactType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtifactType = `-- name: DeleteArtifactType :exec
DELETE FROM registry_artifact_type WHERE id = $1
`

func (q *Queries) DeleteArtifactType(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArtifactType, id)
	return err
}

const getArtifactType = `-- name: GetArtifactType :one
SELECT id, name, description, created_at, updated_at FROM registry_artifact_type WHERE id = $1
`

func (q *Queries) GetArtifactType(ctx context.Context, id int64) (RegistryArtifactType, error) {
	row := q.db.QueryRow(ctx, getArtifactType, id)
	var i RegistryArtifactType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactTypeByName = `-- name: GetArtifactTypeByName :one
SELECT id, name, description, created_at, updated_at FROM registry_artifact_type WHERE name = $1
`

func (q *Queries) GetArtifactTypeByName(ctx context.Context, name string) (RegistryArtifactType, error) {
	row := q.db.QueryRow(ctx, getArtifactTypeByName, name)
	var i RegistryArtifactType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactTypes = `-- name: ListArtifactTypes :many
SELECT id, name, description, created_at, updated_at FROM registry_artifact_type
ORDER BY name ASC
`

func (q *Queries) ListArtifactTypes(ctx context.Context) ([]RegistryArtifactType, error) {
	rows, err := q.db.Query(ctx, listArtifactTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifactType
	for rows.Next() {
		var i RegistryArtifactType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactType = `-- name: UpdateArtifactType :one
UPDATE registry_artifact_type
SET name        = $2,
    description = $3,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateArtifactTypeParams struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateArtifactType(ctx context.Context, arg UpdateArtifactTypeParams) (RegistryArtifactType, error) {
	row := q.db.QueryRow(ctx, updateArtifactType, arg.ID, arg.Name, arg.Description)
	var i RegistryArtifactType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
