// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry_files.sql

package db

import (
	"context"
)

const createArtifactFile = `-- name: CreateArtifactFile :one
INSERT INTO registry_artifact_file (version_id, name, content_type, storage_backend, storage_path, status)
VALUES ($1, $2, $3, $4, $5, 'PENDING')
RETURNING id, version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at
`

type CreateArtifactFileParams struct {
	VersionID      int64   `json:"version_id"`
	Name           string  `json:"name"`
	ContentType    *string `json:"content_type"`
	StorageBackend string  `json:"storage_backend"`
	StoragePath    string  `json:"storage_path"`
}

func (q *Queries) CreateArtifactFile(ctx context.Context, arg CreateArtifactFileParams) (RegistryArtifactFile, error) {
	row := q.db.QueryRow(ctx, createArtifactFile,
		arg.VersionID,
		arg.Name,
		arg.ContentType,
		arg.StorageBackend,
		arg.StoragePath,
	)
	var i RegistryArtifactFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArtifactFile = `-- name: DeleteArtifactFile :exec
DELETE FROM registry_artifact_file WHERE id = $1
`

func (q *Queries) DeleteArtifactFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteArtifactFile, id)
	return err
}

const getArtifactFile = `-- name: GetArtifactFile :one
SELECT id, version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at FROM registry_artifact_file WHERE id = $1
`

func (q *Queries) GetArtifactFile(ctx context.Context, id int64) (RegistryArtifactFile, error) {
	row := q.db.QueryRow(ctx, getArtifactFile, id)
	var i RegistryArtifactFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactFiles = `-- name: ListArtifactFiles :many
SELECT id, version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at FROM registry_artifact_file
WHERE version_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListArtifactFiles(ctx context.Context, versionID int64) ([]RegistryArtifactFile, error) {
	rows, err := q.db.Query(ctx, listArtifactFiles, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryArtifactFile
	for rows.Next() {
		var i RegistryArtifactFile
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Name,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageBackend,
			&i.StoragePath,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableS3FilePaths = `-- name: ListAvailableS3FilePaths :many
SELECT storage_path FROM registry_artifact_file
WHERE storage_backend = 'S3' AND status = 'AVAILABLE'
ORDER BY id
`

// storage_path values for every available S3-backed file, used to drive the S3
// prefix migration Job (internal/storage/migrate.go): the DB is the exact manifest
// of keys this instance owns, so migration never has to list bucket contents.
func (q *Queries) ListAvailableS3FilePaths(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAvailableS3FilePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_path string
		if err := rows.Scan(&storage_path); err != nil {
			return nil, err
		}
		items = append(items, storage_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactFileStatus = `-- name: UpdateArtifactFileStatus :exec
UPDATE registry_artifact_file
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateArtifactFileStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateArtifactFileStatus(ctx context.Context, arg UpdateArtifactFileStatusParams) error {
	_, err := q.db.Exec(ctx, updateArtifactFileStatus, arg.ID, arg.Status)
	return err
}

const updateArtifactFileStored = `-- name: UpdateArtifactFileStored :one
UPDATE registry_artifact_file
SET storage_path = $2,
    size_bytes   = $3,
    status       = $4,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, version_id, name, content_type, size_bytes, storage_backend, storage_path, status, created_at, updated_at
`

type UpdateArtifactFileStoredParams struct {
	ID          int64  `json:"id"`
	StoragePath string `json:"storage_path"`
	SizeBytes   *int64 `json:"size_bytes"`
	Status      string `json:"status"`
}

func (q *Queries) UpdateArtifactFileStored(ctx context.Context, arg UpdateArtifactFileStoredParams) (RegistryArtifactFile, error) {
	row := q.db.QueryRow(ctx, updateArtifactFileStored,
		arg.ID,
		arg.StoragePath,
		arg.SizeBytes,
		arg.Status,
	)
	var i RegistryArtifactFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageBackend,
		&i.StoragePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
