// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package db

import (
	"context"
)

const countJobsForTemplate = `-- name: CountJobsForTemplate :one
SELECT COUNT(*)
FROM job j
JOIN job_template_version jtv ON j.template_version_id = jtv.id
WHERE jtv.template_id = $1
`

func (q *Queries) CountJobsForTemplate(ctx context.Context, templateID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsForTemplate, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTemplates = `-- name: CountTemplates :one
SELECT COUNT(*) FROM job_template
`

func (q *Queries) CountTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO job_template (name, description, docker_image, latest_version_number)
VALUES ($1, $2, $3, 0)
RETURNING id, name, description, docker_image, latest_version_number, created_at, updated_at
`

type CreateTemplateParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	DockerImage string  `json:"docker_image"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (JobTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.Name, arg.Description, arg.DockerImage)
	var i JobTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DockerImage,
		&i.LatestVersionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplateVersion = `-- name: CreateTemplateVersion :one
INSERT INTO job_template_version (template_id, version_number, docker_image, default_run_config, changelog)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, template_id, version_number, docker_image, default_run_config, changelog, created_at
`

type CreateTemplateVersionParams struct {
	TemplateID       int64   `json:"template_id"`
	VersionNumber    int32   `json:"version_number"`
	DockerImage      string  `json:"docker_image"`
	DefaultRunConfig *string `json:"default_run_config"`
	Changelog        *string `json:"changelog"`
}

func (q *Queries) CreateTemplateVersion(ctx context.Context, arg CreateTemplateVersionParams) (JobTemplateVersion, error) {
	row := q.db.QueryRow(ctx, createTemplateVersion,
		arg.TemplateID,
		arg.VersionNumber,
		arg.DockerImage,
		arg.DefaultRunConfig,
		arg.Changelog,
	)
	var i JobTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.DockerImage,
		&i.DefaultRunConfig,
		&i.Changelog,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM job_template WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, description, docker_image, latest_version_number, created_at, updated_at FROM job_template WHERE id = $1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id int64) (JobTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i JobTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DockerImage,
		&i.LatestVersionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, name, description, docker_image, latest_version_number, created_at, updated_at FROM job_template WHERE name = $1
`

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (JobTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, name)
	var i JobTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DockerImage,
		&i.LatestVersionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateVersion = `-- name: GetTemplateVersion :one
SELECT id, template_id, version_number, docker_image, default_run_config, changelog, created_at FROM job_template_version
WHERE template_id = $1 AND version_number = $2
`

type GetTemplateVersionParams struct {
	TemplateID    int64 `json:"template_id"`
	VersionNumber int32 `json:"version_number"`
}

func (q *Queries) GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (JobTemplateVersion, error) {
	row := q.db.QueryRow(ctx, getTemplateVersion, arg.TemplateID, arg.VersionNumber)
	var i JobTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.DockerImage,
		&i.DefaultRunConfig,
		&i.Changelog,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplateVersionByID = `-- name: GetTemplateVersionByID :one
SELECT id, template_id, version_number, docker_image, default_run_config, changelog, created_at FROM job_template_version WHERE id = $1
`

func (q *Queries) GetTemplateVersionByID(ctx context.Context, id int64) (JobTemplateVersion, error) {
	row := q.db.QueryRow(ctx, getTemplateVersionByID, id)
	var i JobTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.VersionNumber,
		&i.DockerImage,
		&i.DefaultRunConfig,
		&i.Changelog,
		&i.CreatedAt,
	)
	return i, err
}

const incrementTemplateVersion = `-- name: IncrementTemplateVersion :one
UPDATE job_template
SET latest_version_number = latest_version_number + 1,
    updated_at             = NOW()
WHERE id = $1
RETURNING latest_version_number
`

func (q *Queries) IncrementTemplateVersion(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementTemplateVersion, id)
	var latest_version_number int32
	err := row.Scan(&latest_version_number)
	return latest_version_number, err
}

const listTemplateVersions = `-- name: ListTemplateVersions :many
SELECT id, template_id, version_number, docker_image, default_run_config, changelog, created_at FROM job_template_version
WHERE template_id = $1
ORDER BY version_number ASC
`

func (q *Queries) ListTemplateVersions(ctx context.Context, templateID int64) ([]JobTemplateVersion, error) {
	rows, err := q.db.Query(ctx, listTemplateVersions, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobTemplateVersion
	for rows.Next() {
		var i JobTemplateVersion
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.VersionNumber,
			&i.DockerImage,
			&i.DefaultRunConfig,
			&i.Changelog,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, description, docker_image, latest_version_number, created_at, updated_at FROM job_template
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListTemplatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]JobTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobTemplate
	for rows.Next() {
		var i JobTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DockerImage,
			&i.LatestVersionNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE job_template
SET description = $2,
    docker_image = $3,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, name, description, docker_image, latest_version_number, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID          int64   `json:"id"`
	Description *string `json:"description"`
	DockerImage string  `json:"docker_image"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (JobTemplate, error) {
	row := q.db.QueryRow(ctx, updateTemplate, arg.ID, arg.Description, arg.DockerImage)
	var i JobTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DockerImage,
		&i.LatestVersionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
