{{- if .Values.auth.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fusion-index.backendServiceName" . }}-tokenreview
  labels:
    {{- include "fusion-index.labels" . | nindent 4 }}
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fusion-index.backendServiceName" . }}-tokenreview
  labels:
    {{- include "fusion-index.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fusion-index.backendServiceName" . }}-tokenreview
subjects:
  - kind: ServiceAccount
    name: {{ include "fusion-index.backendServiceName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
