DROP TABLE IF EXISTS artifact CASCADE;
DROP SEQUENCE IF EXISTS artifact_seq;

DROP TABLE IF EXISTS job_version CASCADE;
DROP SEQUENCE IF EXISTS job_version_seq;

DROP TABLE IF EXISTS job CASCADE;
DROP SEQUENCE IF EXISTS job_seq;

DROP TABLE IF EXISTS job_template_version CASCADE;
DROP SEQUENCE IF EXISTS job_template_version_seq;

DROP TABLE IF EXISTS job_template CASCADE;
DROP SEQUENCE IF EXISTS job_template_seq;
