# Dev overrides
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.devservices.enabled=true
quarkus.s3.devservices.enabled=false

# Use filesystem storage in dev by default
fusion.index.storage.backend=FILESYSTEM
